#!/usr/bin/env bash
# Copyright 2025 IBM

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
  # Display Help
    cat <<EOF
Syntax: $ addVolumes.sh [-h] [-w WORKSPACE_NAME] [-i INSTANCE_NAME] [-p VOLUME_NAME_PREFIX] [-t STORAGE_TIER] [-s VOLUME_SIZE] [-c VOLUME_COUNT] [-e] [-r]
Create volumes and attach them to an LPAR.
The volume names will be a combination of the volume prefix provided and a suffix containing numbers generated by PowerVS.
The volumes will have storage affinity with the instance specified.

  h     print help
  w     the PowerVS workspace name
  i     instance / LPAR name or ID
  p     prefix for the volume names
  t     storage tier value as shown by "ibmcloud pi storage-tiers"
  s     volume size in GB
  c     volume count, the number of volumes to create
  e     create the volumes as shareable and so they can be attached to multiple VSIs. Default: not shared
  r     enables storage replication on the volumes

EOF
}

fatal() {
    echo "FATAL: $*"
    exit 1
}

check_runtime_prereqs() {
    echo "checking prereqs"
    [[ -z "$(which jq)" ]] && fatal "jq is not installed. See https://stedolan.github.io/jq/"
    [[ -z "$(which ibmcloud)" ]] && fatal "ibmcloud CLI is not installed"
    if ! ibmcloud plugin list | grep power-iaas > /dev/null; then
      fatal "The PowerVS CLI plugin is not installed. Install it by running: ibmcloud plugin install power-iaas"
    fi
    ibmcloud iam oauth-tokens > /dev/null 2>&1 || fatal "Please log in with the ibmcloud CLI (ibmcloud login)"
}

target_workspace() {
  echo "Targeting workspace $1"
  workspace_ids=$(ibmcloud pi ws list --json | jq -r '.Payload.workspaces[]? | "\(.details.crn) \(.name)"')
  workspace_found="false"
  while read crn name;
  do
      if [[ "x${name}" == "x${1}" ]]; then
          workspace_found="true"
          ibmcloud pi workspace target $crn
          break  # Exit the loop if the workspace is found
      fi
  done <<< "$workspace_ids"

  if [[ "$workspace_found" != "true" ]]; then
      echo "Workspace ${1} was not found!"
      exit 1
  fi
}

wait_for_volumes_state() {
# parameter $1: comma separated volume list
# parameter $2: desired state
    echo "Waiting for volumes to become $2"
    for volid in ${1//,/ }
    do
        volume_state="creating"
        # Loop until the volume reaches the desired state
        while [ "$volume_state" != "$2" ]
        do
            echo -n "Volume id=$volid"
            volume_details=$(ibmcloud pi vol get $volid --json)
            volume_name=$(echo -n $volume_details | jq -r .name)
            volume_state=$(echo -n $volume_details | jq -r .state)
            echo ", name=$volume_name, state=$volume_state"
            sleep $LOOP_DELAY
        done
    done
}

if [ $# -eq 0 ] ; then
    usage
    exit 0
fi

LOOP_DELAY=2

replication=""
shareable=""
while getopts ":hrei:t:s:c:w:p:" opt; do
  # for each argument present assign the correct value to override the default value
  # values defined after the flag are stored in $OPTARG
  case $opt in
  h) # if -h print usage
    usage
    exit 0
    ;;
  i) vsi_name=$OPTARG ;;
  w) workspace=$OPTARG ;;
  s) size=$OPTARG ;;
  c) count=$OPTARG ;;
  r) replication="--replication-enabled" ;;
  e) shareable="--shareable" ;;
  t) tier=$OPTARG ;;
  p) prefix=$OPTARG ;;

  \?) # this case is for when an unknown argument is passed
    echo "Invalid option: -$OPTARG"
    exit 1
    ;;
  esac
done

[[ -z "$vsi_name" ]] && fatal "The instance/LPAR name or ID is required on the -i parameter"
[[ -z "$workspace" ]] && fatal "The PowerVS workspace name is required with the -w parameter"
[[ -z "$tier" ]] && fatal "The storage tier is required with the -t parameter"
[[ -z "$count" ]] && fatal "The volume count is required with the -c parameter"
[[ -z "$size" ]] && fatal "The volume size is required with the -s parameter"
[[ -z "$prefix" ]] && fatal "The volume name prefix is required with the -p parameter"

check_runtime_prereqs
target_workspace $workspace

# Create the volumes
volume_create_output=$(ibmcloud pi vol cr $prefix -s $size -c $count $replication $shareable -t $tier --affinity-policy affinity --affinity-instance $vsi_name --json)
volume_list=$(echo -n $volume_create_output | jq -r '.volumes | map(.volumeID) | join(",")')
wait_for_volumes_state $volume_list "available"

# Attach the volumes wait until they are all attached (in-use)
ibmcloud pi ins vol attach $vsi_name --volumes $volume_list
wait_for_volumes_state $volume_list "in-use"

echo "Done"