#!/usr/bin/env bash

# Copyright 2025 IBM

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


usage() {
  # Display Help
    cat <<EOF
Syntax: $ icpiwstg WORKSPACENAME
Target the workspace
EOF
}

fatal() {
    echo "FATAL: $*"
    exit 1
}

check_runtime_prereqs() {
    echo "checking prereqs"
    [[ -z "$(which jq)" ]] && fatal "jq is not installed. See https://stedolan.github.io/jq/"
    [[ -z "$(which ibmcloud)" ]] && fatal "ibmcloud CLI is not installed"
    if ! ibmcloud plugin list | grep power-iaas > /dev/null; then
      fatal "The PowerVS CLI plugin is not installed. Install it by running: ibmcloud plugin install power-iaas"
    fi
    ibmcloud iam oauth-tokens > /dev/null 2>&1 || fatal "Please log in with the ibmcloud CLI (ibmcloud login)"
}

target_workspace() {
  echo "Targeting workspace $1"
  workspace_ids=$(ibmcloud pi ws list --json | jq -r '.Payload.workspaces[]? | "\(.details.crn) \(.name)"')
  workspace_found="false"
  while read crn name;
  do
      if [[ "x${name}" == "x${1}" ]]; then
          workspace_found="true"
          ibmcloud pi workspace target $crn
          break  # Exit the loop if the workspace is found
      fi
  done <<< "$workspace_ids"

  if [[ "$workspace_found" != "true" ]]; then
      echo "Workspace ${1} was not found!"
      exit 1
  fi
}

if [ $# -eq 0 ] ; then
    usage
    exit 0
fi

if [[ "-h" == "${1}" ]]; then
    usage
    exit 0
fi

check_runtime_prereqs
target_workspace $1
